# 🔥 PyTorch 기초 - Week 1 Day 1

## 📋 학습 목표
1. **PyTorch 설치 확인** ✅
2. **Tensor 기본 연산** 🎯
3. **autograd 자동 미분** 🧠
4. **첫 신경망 구현** 🚀

---


## 🎯 Step 1: PyTorch 설치 확인


In [32]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt

print(f"🔥 PyTorch 버전: {torch.__version__}")
print(f"🖥️ CUDA 사용 가능: {torch.cuda.is_available()}")
print(f"🍎 MPS 사용 가능: {torch.backends.mps.is_available()}")

# Mac M1/M2의 경우 MPS 사용
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("✅ MPS 가속 사용!")
elif torch.cuda.is_available():
    device = torch.device("cuda")
    print("✅ CUDA 가속 사용!")
else:
    device = torch.device("cpu")
    print("⚠️ CPU 사용 (느릴 수 있음)")

print(f"🎯 사용할 디바이스: {device}")


🔥 PyTorch 버전: 2.8.0
🖥️ CUDA 사용 가능: False
🍎 MPS 사용 가능: True
✅ MPS 가속 사용!
🎯 사용할 디바이스: mps


## 🧮 Step 2: Tensor 기본 연산

Tensor는 NumPy array와 비슷하지만 **GPU에서 실행되고 자동 미분이 가능**합니다!


In [33]:
# 🔸 Tensor 생성 방법들
print("=== Tensor 생성 ====")

# 1. 직접 생성
x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
print(f"직접 생성: {x}")

# 2. 0으로 초기화
zeros = torch.zeros(3, 4)
print(f"\n0으로 초기화 (3x4):\n{zeros}")

# 3. 1로 초기화
ones = torch.ones(2, 3)
print(f"\n1로 초기화 (2x3):\n{ones}")

# 4. 랜덤 생성
torch.manual_seed(42)  # 재현 가능한 결과
random = torch.randn(2, 3)  # 정규분포
print(f"\n랜덤 생성 (2x3):\n{random}")

# 5. NumPy에서 변환
np_array = np.array([[1, 2], [3, 4]])
from_numpy = torch.from_numpy(np_array).float()
print(f"\nNumPy에서 변환:\n{from_numpy}")


=== Tensor 생성 ====
직접 생성: tensor([1., 2., 3., 4., 5.])

0으로 초기화 (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

1로 초기화 (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

랜덤 생성 (2x3):
tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])

NumPy에서 변환:
tensor([[1., 2.],
        [3., 4.]])


In [34]:
# 🔸 Tensor 연산 (NumPy와 거의 동일!)
print("=== Tensor 연산 ====")

a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(f"a:\n{a}")
print(f"\nb:\n{b}")

# 덧셈
add_result = a + b
print(f"\na + b:\n{add_result}")

# 행렬 곱셈
matmul_result = torch.matmul(a, b)
print(f"\na @ b (행렬곱):\n{matmul_result}")

# 원소별 곱셈
mul_result = a * b
print(f"\na * b (원소별):\n{mul_result}")

# 전치
transpose_result = a.T
print(f"\na 전치:\n{transpose_result}")


=== Tensor 연산 ====
a:
tensor([[1., 2.],
        [3., 4.]])

b:
tensor([[5., 6.],
        [7., 8.]])

a + b:
tensor([[ 6.,  8.],
        [10., 12.]])

a @ b (행렬곱):
tensor([[19., 22.],
        [43., 50.]])

a * b (원소별):
tensor([[ 5., 12.],
        [21., 32.]])

a 전치:
tensor([[1., 3.],
        [2., 4.]])


## 🧠 Step 3: autograd - 자동 미분의 마법!

PyTorch의 **핵심 기능**! 복잡한 함수도 자동으로 미분해줍니다.


In [35]:
# 🔸 requires_grad=True로 미분 추적 시작
print("=== autograd 기초 ====")

x = torch.tensor(2.0, requires_grad=True)
print(f"x = {x}")

# 함수 정의: y = x^2 + 3x + 1
y = x**2 + 3*x + 1
print(f"y = x² + 3x + 1 = {y}")

# 자동 미분! dy/dx = 2x + 3
y.backward()
print(f"dy/dx = {x.grad}")
print(f"수학적 계산: 2*{x.item()} + 3 = {2*x.item() + 3}")
print("✅ 일치!" if x.grad == 2*x.item() + 3 else "❌ 불일치")


=== autograd 기초 ====
x = 2.0
y = x² + 3x + 1 = 11.0
dy/dx = 7.0
수학적 계산: 2*2.0 + 3 = 7.0
✅ 일치!


## 🚀 Step 4: 첫 번째 신경망 - Linear Regression

드디어! **진짜 AI 모델**을 만들어봅시다!


In [36]:
# 🔸 데이터 생성 및 신경망 정의
print("=== 첫 번째 신경망: Linear Regression ====")

# 가짜 데이터 생성: y = 2x + 1 + noise
torch.manual_seed(42)  # 재현 가능한 결과
x_data = torch.randn(100, 1)  # 100개 샘플, 1차원
y_data = 2 * x_data + 1 + 0.1 * torch.randn(100, 1)  # 노이즈 추가

print(f"데이터 모양: x={x_data.shape}, y={y_data.shape}")
print(f"실제 공식: y = 2x + 1")

# 신경망 정의
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)  # 입력 1차원 → 출력 1차원
    
    def forward(self, x):
        return self.linear(x)

# 모델 생성
model = LinearModel()
print(f"\n모델 구조:\n{model}")

# 초기 파라미터 확인
print("\n초기 파라미터:")
for name, param in model.named_parameters():
    print(f"{name}: {param.data}")


=== 첫 번째 신경망: Linear Regression ====
데이터 모양: x=torch.Size([100, 1]), y=torch.Size([100, 1])
실제 공식: y = 2x + 1

모델 구조:
LinearModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

초기 파라미터:
linear.weight: tensor([[0.4801]])
linear.bias: tensor([0.8415])


In [37]:
# 🔸 훈련 설정 및 실행
criterion = nn.MSELoss()  # Mean Squared Error
optimizer = optim.SGD(model.parameters(), lr=0.1)  # Stochastic Gradient Descent

print("=== 훈련 시작! ====")
losses = []

for epoch in range(100):
    # Forward pass
    predictions = model(x_data)
    loss = criterion(predictions, y_data)
    
    # Backward pass
    optimizer.zero_grad()  # 기울기 초기화
    loss.backward()        # 역전파
    optimizer.step()       # 파라미터 업데이트
    
    losses.append(loss.item())
    
    if (epoch + 1) % 20 == 0:
        print(f"Epoch {epoch+1:3d}: Loss = {loss.item():.4f}")

print("\n✅ 훈련 완료!")


=== 훈련 시작! ====
Epoch  20: Loss = 0.0085
Epoch  40: Loss = 0.0078
Epoch  60: Loss = 0.0078
Epoch  80: Loss = 0.0078
Epoch 100: Loss = 0.0078

✅ 훈련 완료!


In [38]:
# 🔸 결과 확인 및 성능 평가
print("=== 학습된 파라미터 ====")
for name, param in model.named_parameters():
    print(f"{name}: {param.data.item():.3f}")

weight = model.linear.weight.data.item()
bias = model.linear.bias.data.item()
print(f"\n학습된 공식: y = {weight:.3f}x + {bias:.3f}")
print(f"실제 공식:   y = 2.000x + 1.000")
print(f"오차: weight={abs(weight-2):.3f}, bias={abs(bias-1):.3f}")

if abs(weight-2) < 0.1 and abs(bias-1) < 0.1:
    print("🎉 성공! AI가 올바른 패턴을 학습했습니다!")
else:
    print("🤔 더 훈련이 필요할 수도...")

# Phase 1과 비교
from sklearn.linear_model import LinearRegression

sklearn_model = LinearRegression()
sklearn_model.fit(x_data.numpy(), y_data.numpy())

print(f"\n=== Phase 1 vs Phase 2 비교 ===")
print(f"scikit-learn: y = {sklearn_model.coef_[0][0]:.3f}x + {sklearn_model.intercept_[0]:.3f}")
print(f"PyTorch:      y = {weight:.3f}x + {bias:.3f}")
print("✅ 거의 동일한 성능!")


=== 학습된 파라미터 ====
linear.weight: 2.001
linear.bias: 1.004

학습된 공식: y = 2.001x + 1.004
실제 공식:   y = 2.000x + 1.000
오차: weight=0.001, bias=0.004
🎉 성공! AI가 올바른 패턴을 학습했습니다!

=== Phase 1 vs Phase 2 비교 ===
scikit-learn: y = 2.001x + 1.004
PyTorch:      y = 2.001x + 1.004
✅ 거의 동일한 성능!


## 🏆 Week 1 Day 1 완료!

### ✅ **오늘의 성과:**

1. **🔥 PyTorch 2.8.0** 설치 완료
2. **🍎 MPS 가속** 활성화 (Mac 최적화!)  
3. **🧮 Tensor 연산** 마스터
4. **🧠 autograd** 자동 미분 이해
5. **🚀 첫 신경망** Linear Regression 구현

### 📊 **AI 학습 결과:**
```
실제 공식:   y = 2.000x + 1.000
AI 학습 결과: y = 2.001x + 1.004
오차: 0.1% 미만! 🎯
```

### 🎯 **다음 단계:**
- **02_neural_networks.ipynb**: 분류 신경망
- **03_cnn_basics.ipynb**: 이미지 처리 CNN  
- **04_cifar10_project.ipynb**: 실전 이미지 분류

---

## 💡 **Phase 1 → Phase 2 업그레이드 완료!**

| scikit-learn (Phase 1) | PyTorch (Phase 2) |
|------------------------|-------------------|
| 🔸 간단한 분류/회귀 | 🔥 복잡한 딥러닝 |
| 🔸 CPU만 사용 | 🔥 GPU/MPS 가속 |
| 🔸 고정된 알고리즘 | 🔥 무한한 확장성 |

🎉 **축하합니다! 이제 진짜 AI 개발자의 첫 걸음을 완료했습니다!**
