# 📊 NumPy 기초 - AI를 위한 데이터 처리

NumPy는 파이썬에서 수치 연산을 위한 핵심 라이브러리입니다.
AI/ML에서 데이터를 다룰 때 필수적으로 사용됩니다.

## 🎯 학습 목표
- NumPy 배열(ndarray) 이해하기
- 배열 생성과 조작 방법
- 수학적 연산과 함수들
- AI에서 자주 사용되는 패턴들


In [1]:
import numpy as np
print(f"NumPy 버전: {np.__version__}")


NumPy 버전: 2.3.3


## 1. NumPy 배열 생성하기


In [2]:
# 리스트에서 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])
print("1차원 배열:", arr1)
print("타입:", type(arr1))
print("형태:", arr1.shape)

# 2차원 배열 (행렬)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2차원 배열:")
print(arr2)
print("형태:", arr2.shape)  # (행, 열)


1차원 배열: [1 2 3 4 5]
타입: <class 'numpy.ndarray'>
형태: (5,)

2차원 배열:
[[1 2 3]
 [4 5 6]]
형태: (2, 3)


In [4]:
# AI에서 자주 사용되는 배열 생성
zeros = np.zeros((3, 4))      # 0으로 채운 배열
ones = np.ones((2, 3))        # 1로 채운 배열
random_arr = np.random.random((2, 3))  # 랜덤 값 (0~1)

print("0 배열:\n", zeros)
print("\n1 배열:\n", ones)
print("\n랜덤 배열:\n", random_arr)

# 범위 생성 (AI에서 많이 사용)
range_arr = np.arange(0, 10, 2)  # 0부터 10까지 2씩 증가
linspace_arr = np.linspace(0, 1, 5)  # 0부터 1까지 5개 균등분할
print("\n범위 배열:", range_arr)
print("균등분할:", linspace_arr)


0 배열:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

1 배열:
 [[1. 1. 1.]
 [1. 1. 1.]]

랜덤 배열:
 [[0.62252177 0.56194406 0.26918108]
 [0.15441716 0.51832046 0.76289958]]

범위 배열: [0 2 4 6 8]
균등분할: [0.   0.25 0.5  0.75 1.  ]


## 2. 핵심 연산들 (AI에서 가장 중요!)


In [5]:
# 벡터 연산 (AI의 핵심!)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("벡터 a:", a)
print("벡터 b:", b)
print("덧셈:", a + b)
print("내적 (dot product):", np.dot(a, b))  # AI에서 매우 중요!

# 행렬 연산 (딥러닝의 기본!)
X = np.array([[1, 2], [3, 4]])  # 입력 데이터
W = np.array([[0.5, 0.3], [0.2, 0.8]])  # 가중치

result = X @ W  # 행렬 곱셈 (신경망의 기본 연산)
print("\n행렬 곱셈 결과:")
print(result)

# 통계 함수들 (데이터 분석 필수)
data = np.random.randint(1, 100, 10)
print(f"\n데이터: {data}")
print(f"평균: {np.mean(data):.2f}")
print(f"표준편차: {np.std(data):.2f}")
print(f"최댓값: {np.max(data)}, 최솟값: {np.min(data)}")


벡터 a: [1 2 3]
벡터 b: [4 5 6]
덧셈: [5 7 9]
내적 (dot product): 32

행렬 곱셈 결과:
[[0.9 1.9]
 [2.3 4.1]]

데이터: [13 95 33 57 62 12 95 77 42 43]
평균: 52.90
표준편차: 28.47
최댓값: 95, 최솟값: 12
